name: Windows-CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ contains(github.ref, 'merge')}}
permissions:
  contents: read
run-name: ${{ github.ref_name }} - ${{ github.run_number }}
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  GIT_CONFIG_PARAMETERS: '''core.autocrlf=false'''
  NugetSecurityAnalysisWarningLevel: none
  POWERSHELL_TELEMETRY_OPTOUT: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none
  SYSTEM_ARTIFACTSDIRECTORY: ${{ github.workspace }}/artifacts
  BUILD_ARTIFACTSTAGINGDIRECTORY: ${{ github.workspace }}/artifacts
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
jobs:
  changes:
    name: Change Detection
    runs-on: self-hosted
    if: startsWith(github.repository_owner, 'azure') || true
    permissions:
      pull-requests: read
      contents: read
    outputs:
      source: ${{ steps.filter.outputs.source }}
      buildModuleChanged: ${{ steps.filter.outputs.buildModuleChanged }}
      packagingChanged: ${{ steps.filter.outputs.packagingChanged }}
    steps:
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Change Detection
      id: filter
      uses: ./.github/actions/infrastructure/path-filters
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 6
  ready_to_merge:
    name: windows ready to merge
    if: ${{ !cancelled() && (always()) }}
    uses: PowerShell/compliance/.github/workflows/ready-to-merge.yml@c8b3ad5819ad7078f3e375519b4f8c6232d1cbdf
    with:
      needs_context: ${{ toJson(needs) }}
    timeout-minutes: 6
'on':
  workflow_dispatch: null
  push:
    branches:
    - master
    - release/**
    - github-mirror
    - servicing-*
    paths:
    - '**'
    - '*'
    - .globalconfig
    - '!.vsts-ci/misc-analysis.yml'
    - '!.github/ISSUE_TEMPLATE/**'
    - '!.dependabot/config.yml'
    - '!test/perf/**'
    - '!.pipelines/**'
  pull_request:
    branches:
    - master
    - release/**
    - github-mirror
    - servicing-*
    - '*-feature'
